version: "3.5"

services:
########################### POSTGRES DATABASE
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    hostname: db
    environment:
      - POSTGRES_USER=${ROOT_DB_USER}
      - POSTGRES_PASSWORD=${ROOT_DB_PASSWORD}
      # - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./postgres-data:/var/lib/postgresql/data # Change ./postgres-data to another directory if you don't want to use the default docker volume
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "300MB"

########################### KAFKA
  zookeeper:
    image: 'wurstmeister/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "400MB"
  
  kafka:
    image: 'wurstmeister/kafka:latest'
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_CREATE_TOPICS: "consumer:1:1,topic2:1:1:compact"
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1GB"

  kafka-ui:
    container_name: kafka-ui
    image: tchiotludo/akhq
    network_mode: host # Served on lcoalhost:8080 (Can not change due to network_mode)
    depends_on:
      - zookeeper
      - kafka
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            my-cluster:
              properties:
                bootstrap.servers: "localhost:9092"

###########################REDIS STACK (Server + RedisInsight)
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
     - "6379:6379"
     - "8001:8001"
    # volumes:
    #   - ${PWD}/redis/data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "500MB"

###########################SFTP
  sftp:
    image: atmoz/sftp:latest
    platform: linux/x86_64
    container_name: sftp
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    expose:
      - "22"
    ports:
      - "22:22"
    command:
      - rootuser:password:100:100:cdpna
    volumes:
      - ${PWD}/sftp/data/:/home/rootuser/cdpna
#      - ${PWD}/sftp/bindmount.sh:/etc/sftp.d/bindmount.sh
      - ${PWD}/sftp/keys/ssh_host_rsa_key.pub:/home/root/.ssh/ssh_host_rsa_key.pub:ro
      - ${PWD}/sftp/keys/ssh_host_ed25519_key.pub:/home/root/.ssh/ssh_host_ed25519_key.pub:ro
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"

###########################Portainer - Docker UI
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9443:9443
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"

networks:
  default:
    driver: bridge
    name: backbone-for-testing